rococolab:
- desk_shared
- desk_shared_0
- desk_shared_1
- desk_shared_2
- desk_shared_3
- desk_shared_4
- desk_shared_5
- desk_shared_6
- desk_shared_7
- monitor_pc
- monitor_pc_0
- monitor_pc_1
- books
- books_0
- books_1
- drawer
- drawer_0
- office_chair
- office_chair_0
- office_chair_1
- office_chair_2
- office_chair_3
- office_chair_4
- office_chair_5
- chair_foldable
- chair_foldable_0
- chair_foldable_1
- chair_foldable_2
- chair_foldable_3
- chair_foldable_4
- shelf
- shelf_0
- pc
- grass_robocup
