phdoffice:
- desk_shared
- desk_shared_0
- desk_shared_1
- desk_shared_2
- desk_shared_3
- desk_shared_4
- desk_shared_5
- desk_shared_6
- desk_shared_7
- desk_shared_8
- desk_shared_9
- desk_shared_10
- boxes
- office_chair
- office_chair_0
- office_chair_1
- office_chair_2
- office_chair_3
- office_chair_4
- office_chair_5
- office_chair_6
- office_chair_7
- office_chair_8
- office_chair_9
- office_chair_10
- drawer
- shelf
- microwave
- rack_coat
- monitor_pc
- monitor_pc_0
- monitor_pc_1
- monitor_pc_2
- monitor_pc_3
- monitor_pc_4
- monitor_pc_5
- monitor_pc_6
- monitor_pc_7
- monitor_pc_8
- monitor_pc_9
- monitor_pc_10
- books
